Script started on 2021-08-27 10:00:17-06:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="85" LINES="13"]
]0;spike@SpikeDaComputer: ~/CSE113/lab0[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab0[00m$ gcc- g[K[K[K -g -Wall hello.c -o hello
]0;spike@SpikeDaComputer: ~/CSE113/lab0[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab0[00m$ ./hella[Ko
Hello, World!
]0;spike@SpikeDaComputer: ~/CSE113/lab0[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab0[00m$ exit
exit

Script done on 2021-08-27 10:01:03-06:00 [COMMAND_EXIT_CODE="0"]
