Script started on 2022-04-25 19:40:24-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="103" LINES="10"]
]0;spike@SpikeDaComputer: ~/cse122/blackbox/blackbox[01;32mspike@SpikeDaComputer[00m:[01;34m~/cse122/blackbox/blackbox[00m$ code .[4Plscd blackboxls[Kcd cse122[3Pode .d cse122ls[Kcd blackboxls[Kcode .[Kcode .[4Plscode .[Kvalgring [K[Kd ./main
==3998== Memcheck, a memory error detector
==3998== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==3998== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==3998== Command: ./main
==3998== 
Enter the size you want the list to be
10
Do you want an in order (1), reverse order (2), or shuffled array (3)?
Enter your choice: 3
Which of the functions do you want to test 1,2,3,4,5,6, or 7?
Enter your choice: 4
4) Time taken: 0.274 seconds
4) CPU time elapsed: 274718 ticks
==3998== 
==3998== HEAP SUMMARY:
==3998==     in use at exit: 0 bytes in 0 blocks
==3998==   total heap usage: 5 allocs, 5 frees, 2,288 bytes allocated
==3998== 
==3998== All heap blocks were freed -- no leaks are possible
==3998== 
==3998== For lists of detected and suppressed errors, rerun with: -s
==3998== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;spike@SpikeDaComputer: ~/cse122/blackbox/blackbox[01;32mspike@SpikeDaComputer[00m:[01;34m~/cse122/blackbox/blackbox[00m$ exit
exit

Script done on 2022-04-25 19:40:57-06:00 [COMMAND_EXIT_CODE="0"]
