Script started on 2021-11-07 19:56:45-07:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="85" LINES="12"]
]0;spike@SpikeDaComputer: ~/CSE113/lab8[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab8[00m$ ./lab8
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
1
Where do you want to add your number?
1) Head of the list
2) Somewhere in the middle
3) Tail of the list
1
Enter the number you want to add
2
This is the value stored 2.000000
This is the address of the node 0x55ba78f20ac0
The address next points to is NULL
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
1
Where do you want to add your number?
1) Head of the list
2) Somewhere in the middle
3) Tail of the list
2
Enter the number you want to add
3
Enter where you want to add the number
2
This is the value stored 3.000000
This is the address of the node 0x55ba78f20ae0
The address next points to is NULL
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
1
Where do you want to add your number?
1) Head of the list
2) Somewhere in the middle
3) Tail of the list
3
Enter the number you want to add
5
This is the value stored 5.000000
This is the address of the node 0x55ba78f20b00
The address next points to is NULL
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
3
This is the value stored 2.000000
This is the address of the node 0x55ba78f20ac0
This is the address that next points to 0x55ba78f20ae0
This is the value stored 3.000000
This is the address of the node 0x55ba78f20ae0
This is the address that next points to 0x55ba78f20b00
This is the value stored 5.000000
This is the address of the node 0x55ba78f20b00
The address next points to is NULL
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
2
Enter the number you want to delete
3
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
3
This is the value stored 2.000000
This is the address of the node 0x55ba78f20ac0
This is the address that next points to 0x55ba78f20b00
This is the value stored 5.000000
This is the address of the node 0x55ba78f20b00
The address next points to is NULL
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
4
There are 2 nodes in this list
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
5
Enter the number you want to find in the list
5
The number was found in the list--
This is the value stored 5.000000
This is the address of the node 0x55ba78f20b00
The address next points to is NULL
Enter your choice
1) Enter a new number
2) Delete a number
3) Print all numbers
4) Tell how many numbers are in the list
5) Find if a number is in the list
6) Quit
6
Laters
]0;spike@SpikeDaComputer: ~/CSE113/lab8[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab8[00m$ exit
exit

Script done on 2021-11-07 19:57:57-07:00 [COMMAND_EXIT_CODE="0"]
