Script started on 2021-10-10 12:26:47-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="131" LINES="11"]
]0;spike@SpikeDaComputer: ~/CSE113/lab5[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab5[00m$ ./lab5_q3
Input the starting point in the form x, y as a double.
6.0, 4.0
Input the ending point in the form x, y as a double.
8.0, 10.0
The euclidean distance is - 6.000000
The manhattan distance is - 8.000000
]0;spike@SpikeDaComputer: ~/CSE113/lab5[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab5[00m$ exit
exit

Script done on 2021-10-10 12:27:33-06:00 [COMMAND_EXIT_CODE="0"]
