Script started on 2021-10-29 10:02:21-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="100" LINES="11"]
]0;spike@SpikeDaComputer: ~/CSE113/lab7/lab7[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab7/lab7[00m$ valgrind version[8P-versionversion valgrind[1P[C[C[C[C[C[C[C[C[C[C[C[C[1@s[C[C[C[C[C[C[C[C[C[C[C[C[8P-versionvalgrind version[Kvalgrind ./dynamic
==10019== Memcheck, a memory error detector
==10019== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10019== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==10019== Command: ./dynamic
==10019== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==10019== 
==10019== HEAP SUMMARY:
==10019==     in use at exit: 0 bytes in 0 blocks
==10019==   total heap usage: 2 allocs, 2 frees, 1,067 bytes allocated
==10019== 
==10019== All heap blocks were freed -- no leaks are possible
==10019== 
==10019== For lists of detected and suppressed errors, rerun with: -s
==10019== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;spike@SpikeDaComputer: ~/CSE113/lab7/lab7[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab7/lab7[00m$ exit
exit

Script done on 2021-10-29 10:02:43-06:00 [COMMAND_EXIT_CODE="0"]
