Script started on 2021-10-29 10:03:32-06:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="100" LINES="11"]
]0;spike@SpikeDaComputer: ~/CSE113/lab7/lab7[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab7/lab7[00m$ exitvalgrind ./dynamic
==10243== Memcheck, a memory error detector
==10243== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10243== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==10243== Command: ./dynamic
==10243== 
u = "c run, c run unix, run unix run"
u = "c run, c run unix, run unix run, go c, go!"
==10243== 
==10243== HEAP SUMMARY:
==10243==     in use at exit: 43 bytes in 1 blocks
==10243==   total heap usage: 2 allocs, 1 frees, 1,067 bytes allocated
==10243== 
==10243== LEAK SUMMARY:
==10243==    definitely lost: 43 bytes in 1 blocks
==10243==    indirectly lost: 0 bytes in 0 blocks
==10243==      possibly lost: 0 bytes in 0 blocks
==10243==    still reachable: 0 bytes in 0 blocks
==10243==         suppressed: 0 bytes in 0 blocks
==10243== Rerun with --leak-check=full to see details of leaked memory
==10243== 
==10243== For lists of detected and suppressed errors, rerun with: -s
==10243== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;spike@SpikeDaComputer: ~/CSE113/lab7/lab7[01;32mspike@SpikeDaComputer[00m:[01;34m~/CSE113/lab7/lab7[00m$ exit
exit

Script done on 2021-10-29 10:03:40-06:00 [COMMAND_EXIT_CODE="0"]
